/*
------------------------------------------------------------------------------ 
This code was generated by Amplication. 
 
Changes to this file will be lost if the code is regenerated. 

There are other ways to to customize your code, see this doc to learn more
https://docs.amplication.com/how-to/custom-code

------------------------------------------------------------------------------
  */
import * as common from "@nestjs/common";
import * as swagger from "@nestjs/swagger";
import { isRecordNotFoundError } from "../../prisma.util";
import * as errors from "../../errors";
import { Request } from "express";
import { plainToClass } from "class-transformer";
import { ApiNestedQuery } from "../../decorators/api-nested-query.decorator";
import { UrlService } from "../url.service";
import { UrlCreateInput } from "./UrlCreateInput";
import { Url } from "./Url";
import { UrlFindManyArgs } from "./UrlFindManyArgs";
import { UrlWhereUniqueInput } from "./UrlWhereUniqueInput";
import { UrlUpdateInput } from "./UrlUpdateInput";
import { RequestLogFindManyArgs } from "../../requestLog/base/RequestLogFindManyArgs";
import { RequestLog } from "../../requestLog/base/RequestLog";
import { RequestLogWhereUniqueInput } from "../../requestLog/base/RequestLogWhereUniqueInput";
import { RequestParameterFindManyArgs } from "../../requestParameter/base/RequestParameterFindManyArgs";
import { RequestParameter } from "../../requestParameter/base/RequestParameter";
import { RequestParameterWhereUniqueInput } from "../../requestParameter/base/RequestParameterWhereUniqueInput";

export class UrlControllerBase {
  constructor(protected readonly service: UrlService) {}
  @common.Post()
  @swagger.ApiCreatedResponse({ type: Url })
  async createUrl(@common.Body() data: UrlCreateInput): Promise<Url> {
    return await this.service.createUrl({
      data: data,
      select: {
        address: true,
        createdAt: true,
        id: true,
        interval: true,
        updatedAt: true,
      },
    });
  }

  @common.Get()
  @swagger.ApiOkResponse({ type: [Url] })
  @ApiNestedQuery(UrlFindManyArgs)
  async urls(@common.Req() request: Request): Promise<Url[]> {
    const args = plainToClass(UrlFindManyArgs, request.query);
    return this.service.urls({
      ...args,
      select: {
        address: true,
        createdAt: true,
        id: true,
        interval: true,
        updatedAt: true,
      },
    });
  }

  @common.Get("/:id")
  @swagger.ApiOkResponse({ type: Url })
  @swagger.ApiNotFoundResponse({ type: errors.NotFoundException })
  async url(@common.Param() params: UrlWhereUniqueInput): Promise<Url | null> {
    const result = await this.service.url({
      where: params,
      select: {
        address: true,
        createdAt: true,
        id: true,
        interval: true,
        updatedAt: true,
      },
    });
    if (result === null) {
      throw new errors.NotFoundException(
        `No resource was found for ${JSON.stringify(params)}`
      );
    }
    return result;
  }

  @common.Patch("/:id")
  @swagger.ApiOkResponse({ type: Url })
  @swagger.ApiNotFoundResponse({ type: errors.NotFoundException })
  async updateUrl(
    @common.Param() params: UrlWhereUniqueInput,
    @common.Body() data: UrlUpdateInput
  ): Promise<Url | null> {
    try {
      return await this.service.updateUrl({
        where: params,
        data: data,
        select: {
          address: true,
          createdAt: true,
          id: true,
          interval: true,
          updatedAt: true,
        },
      });
    } catch (error) {
      if (isRecordNotFoundError(error)) {
        throw new errors.NotFoundException(
          `No resource was found for ${JSON.stringify(params)}`
        );
      }
      throw error;
    }
  }

  @common.Delete("/:id")
  @swagger.ApiOkResponse({ type: Url })
  @swagger.ApiNotFoundResponse({ type: errors.NotFoundException })
  async deleteUrl(
    @common.Param() params: UrlWhereUniqueInput
  ): Promise<Url | null> {
    try {
      return await this.service.deleteUrl({
        where: params,
        select: {
          address: true,
          createdAt: true,
          id: true,
          interval: true,
          updatedAt: true,
        },
      });
    } catch (error) {
      if (isRecordNotFoundError(error)) {
        throw new errors.NotFoundException(
          `No resource was found for ${JSON.stringify(params)}`
        );
      }
      throw error;
    }
  }

  @common.Get("/:id/requestLogs")
  @ApiNestedQuery(RequestLogFindManyArgs)
  async findRequestLogs(
    @common.Req() request: Request,
    @common.Param() params: UrlWhereUniqueInput
  ): Promise<RequestLog[]> {
    const query = plainToClass(RequestLogFindManyArgs, request.query);
    const results = await this.service.findRequestLogs(params.id, {
      ...query,
      select: {
        createdAt: true,
        id: true,
        response: true,
        status: true,
        timestamp: true,
        updatedAt: true,

        url: {
          select: {
            id: true,
          },
        },
      },
    });
    if (results === null) {
      throw new errors.NotFoundException(
        `No resource was found for ${JSON.stringify(params)}`
      );
    }
    return results;
  }

  @common.Post("/:id/requestLogs")
  async connectRequestLogs(
    @common.Param() params: UrlWhereUniqueInput,
    @common.Body() body: RequestLogWhereUniqueInput[]
  ): Promise<void> {
    const data = {
      requestLogs: {
        connect: body,
      },
    };
    await this.service.updateUrl({
      where: params,
      data,
      select: { id: true },
    });
  }

  @common.Patch("/:id/requestLogs")
  async updateRequestLogs(
    @common.Param() params: UrlWhereUniqueInput,
    @common.Body() body: RequestLogWhereUniqueInput[]
  ): Promise<void> {
    const data = {
      requestLogs: {
        set: body,
      },
    };
    await this.service.updateUrl({
      where: params,
      data,
      select: { id: true },
    });
  }

  @common.Delete("/:id/requestLogs")
  async disconnectRequestLogs(
    @common.Param() params: UrlWhereUniqueInput,
    @common.Body() body: RequestLogWhereUniqueInput[]
  ): Promise<void> {
    const data = {
      requestLogs: {
        disconnect: body,
      },
    };
    await this.service.updateUrl({
      where: params,
      data,
      select: { id: true },
    });
  }

  @common.Get("/:id/requestParameters")
  @ApiNestedQuery(RequestParameterFindManyArgs)
  async findRequestParameters(
    @common.Req() request: Request,
    @common.Param() params: UrlWhereUniqueInput
  ): Promise<RequestParameter[]> {
    const query = plainToClass(RequestParameterFindManyArgs, request.query);
    const results = await this.service.findRequestParameters(params.id, {
      ...query,
      select: {
        createdAt: true,
        id: true,
        name: true,
        updatedAt: true,

        url: {
          select: {
            id: true,
          },
        },

        value: true,
      },
    });
    if (results === null) {
      throw new errors.NotFoundException(
        `No resource was found for ${JSON.stringify(params)}`
      );
    }
    return results;
  }

  @common.Post("/:id/requestParameters")
  async connectRequestParameters(
    @common.Param() params: UrlWhereUniqueInput,
    @common.Body() body: RequestParameterWhereUniqueInput[]
  ): Promise<void> {
    const data = {
      requestParameters: {
        connect: body,
      },
    };
    await this.service.updateUrl({
      where: params,
      data,
      select: { id: true },
    });
  }

  @common.Patch("/:id/requestParameters")
  async updateRequestParameters(
    @common.Param() params: UrlWhereUniqueInput,
    @common.Body() body: RequestParameterWhereUniqueInput[]
  ): Promise<void> {
    const data = {
      requestParameters: {
        set: body,
      },
    };
    await this.service.updateUrl({
      where: params,
      data,
      select: { id: true },
    });
  }

  @common.Delete("/:id/requestParameters")
  async disconnectRequestParameters(
    @common.Param() params: UrlWhereUniqueInput,
    @common.Body() body: RequestParameterWhereUniqueInput[]
  ): Promise<void> {
    const data = {
      requestParameters: {
        disconnect: body,
      },
    };
    await this.service.updateUrl({
      where: params,
      data,
      select: { id: true },
    });
  }
}
